server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: localhost:9092
    demo-topic: demo-topic

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8762/realms/demo
  data:
    redis:
      host: localhost
      port: 6379
      password: password

keycloak:
  url: http://localhost:8762
  admin:
    username: admin
    password: admin
    grant-type: password
    client-id: admin-cli