spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8762/realms/demo

keycloak:
  url: http://188.166.186.82:8762
  admin:
    username: admin
    password: admin
    grant-type: password
    client-id: admin-cli